begin;

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    guild_id bigint not null,
    user_id bigint not null,
    counterparty_id bigint,
    entry_type text not null,
    amount bigint not null default 0,
    currency text not null default 'money',
    description text not null default '',
    meta jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default timezone('utc', now())
);

create index if not exists transactions_user_created_idx
    on public.transactions (guild_id, user_id, created_at desc);

create index if not exists transactions_type_idx
    on public.transactions (entry_type, created_at desc);

alter table if exists public.transactions disable row level security;

grant select, insert, update on table public.transactions to anon, authenticated, service_role;

create table if not exists public.auction_listings (
    id bigint generated by default as identity primary key,
    guild_id bigint not null,
    seller_id bigint not null,
    buyer_id bigint,
    listing_type text not null default 'fixed_price',
    status text not null default 'active',
    item_payload jsonb not null default '{}'::jsonb,
    title text not null default '',
    asking_price bigint not null default 0,
    buyout_price bigint,
    current_bid bigint not null default 0,
    current_bidder_id bigint,
    bid_count integer not null default 0,
    duration_hours integer not null default 24,
    ends_at timestamp with time zone,
    created_at timestamp with time zone not null default timezone('utc', now()),
    updated_at timestamp with time zone not null default timezone('utc', now())
);

create index if not exists auction_listings_guild_status_idx
    on public.auction_listings (guild_id, status, ends_at);

create index if not exists auction_listings_seller_idx
    on public.auction_listings (seller_id, created_at desc);

alter table if exists public.auction_listings disable row level security;

grant select, insert, update on table public.auction_listings to anon, authenticated, service_role;

create table if not exists public.auction_bids (
    id bigint generated by default as identity primary key,
    listing_id bigint not null references public.auction_listings(id) on delete cascade,
    guild_id bigint not null,
    bidder_id bigint not null,
    amount bigint not null,
    created_at timestamp with time zone not null default timezone('utc', now())
);

create index if not exists auction_bids_listing_created_idx
    on public.auction_bids (listing_id, created_at desc);

create index if not exists auction_bids_bidder_idx
    on public.auction_bids (bidder_id, created_at desc);

alter table if exists public.auction_bids disable row level security;

grant select, insert, update on table public.auction_bids to anon, authenticated, service_role;

alter table if exists public.market_guild_states
    add column if not exists weather text;

alter table if exists public.market_guild_states
    add column if not exists time_phase text;

alter table if exists public.market_guild_states
    add column if not exists antiquary_prices jsonb not null default '{}'::jsonb;

alter table if exists public.market_guild_states
    add column if not exists updated_at timestamp with time zone not null default timezone('utc', now());

create index if not exists market_guild_states_updated_at_idx
    on public.market_guild_states (updated_at desc);

alter table if exists public.market_guild_states disable row level security;

grant select, insert, update on table public.market_guild_states to anon, authenticated, service_role;

commit;
